Blog/urls.py
from django.urls import path
from . import views as v
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [ 
    path('', v.blogs, name = "blog"),
    path('categoria/<int:categoria_id>/', v.categoria, name = "categoria"),
]

Carrito/urls.py
from django.urls import path
from . import views as v

app_name = "carro"

urlpatterns = [ 
    path('agregar/<int:producto_id>/', v.agregar_producto, name = "agregar"),
    path('eliminar/<int:producto_id>/', v.eliminar_producto, name = "eliminar"),
    path('restar/<int:producto_id>/', v.restar_producto, name = "restar"),
    path('limpiar/', v.limpiar_carro, name = "limpiar"),
]

ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('servicios/', include('Servicios.urls')),
    path('contacto/', include ('Contacto.urls')),
    path('blog/', include('Blog.urls')),
    path('tienda/', include('Tienda.urls')),
    path('carro/', include('Carrito.urls')),
    path('', include('gestionProyecto.urls')),

]

Tienda/urls.py
  
from django.urls import path
from . import views as v
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [ 
    path('', v.tienda),
    path('categoria/<int:categoria_id>/', v.categoria, name = "p_categoria"),
]

Tienda/models.py
from django.db import models
from django.contrib.auth.models import User



class prueba_Categoria(models.Model):
    nombre = models.CharField(max_length = 15)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.nombre

class T_Producto(models.Model):
    nombre = models.CharField(max_length = 15)
    descripcion = models.CharField(max_length = 50, verbose_name = "Descripción")
    imagen = models.ImageField(upload_to = "producto", null = True, blank = True)
    p_categorias = models.ForeignKey(User, on_delete = models.CASCADE, null = True)
    pro_categorias =  models.ManyToManyField(prueba_Categoria, verbose_name = "Categorias")
    cantidad = models.IntegerField(null = True) 
    precio = models.IntegerField( null = True)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now_add = True)

    class Meta: 
        verbose_name = 'producto'
        verbose_name = 'productos'
    
    def __str__(self):
        return self.nombre
        

Tienda/views.py
from django.shortcuts import render, get_object_or_404
from .models import prueba_Categoria, T_Producto

def tienda(request):
    p = T_Producto.objects.all()
    ctx = {"producto" : p}
  
    return render(request, "Tienda/tienda.html", ctx)

def categoria(request, categoria_id):
    cat = prueba_Categoria.objects.get(id = categoria_id)
    pro = T_Producto.objects.filter(pro_categorias = cat)
    ctx = {'categoria': cat, "producto" : pro}

    return render(request, "Tienda/categoria_pro.html", ctx)

Tienda/templates/carro/widget.html
{% load static %}

<div class = "row">
    <div class="col-lg-12">
        <div class="col-lg-12 col-md-6 col-sm-6 col-12" data-scroll-reveal="enter bottom move 50px over 0.6s after 0.2s">
            <div class="features-small-item">
                <div class="icon">
                    <i><img src="{% static 'gestionProyecto/images/Icons/Colored-icons/png/carrito-de-compras.png' %}" alt=""></i>
                </div>
                <h5 class="features-title">Carrito de compras</h5>
                <table class = "table" >
                    <thead>
                      
                        <tr style = "color: orange;" class = "text-center">
                            <th>Producto</th>
                            <th>Cantidad</th>
                            <th>Suma</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% if request.session.carro.items %}
                            {% for key, value in request.session.carro.items %}
                                <tr class = "text-center">
                                    <td>{{value.nombre}}</td>
                                    <td>{{value.cantidad}}</td>
                                
                                <td>                                   
                                    <a href = "{% url 'carro:eliminar' value.producto_id %}" class="button-red">x</a>
                                    <a href = "{% url 'carro:restar' value.producto_id %}" class="button-orange">-</a>
                                    <a href = "{% url 'carro:agregar' value.producto_id %}" class="button-green">+</a>
                                    {{value.precio}} 
                                </td>
                                </tr>

                            {% endfor %}
                        {% else %}
                            <tr>
                                <td colspan = "3">
                                    <div class="alert alert-danger text-center">
                                        Sin Productos
                                    </div>
                                </td>
                            </tr>
                        {% endif %}
                    

                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="3">
                                <h2><p>Total= ${{importe_total_carro}}</p></h2><hr>
                                <a href = "{% url 'carro:limpiar' %}" class="button-blue">Limpiar</a>
                            </td>
                            
                            
                            
                        </tr>
                        

                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>